Airport/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from SearchEngine import views as myviews
from django.contrib.auth import views as auth_views

# url('^accounts/', include('django.contrib.auth.urls')),
urlpatterns = [
    url(r'^', include('SearchEngine.urls', namespace='searchengine')),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^$', myviews.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^result/(?P<keyword>.+)/$', myviews.recom_redirect, name='recom_redirect'),
]

PubData/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from SearchEngine import views as myviews
from django.contrib.auth import views as auth_views

# url('^accounts/', include('django.contrib.auth.urls')),
urlpatterns = [
    url(r'^', include('SearchEngine.urls', namespace='searchengine')),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^$', myviews.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^result/(?P<keyword>.+)/$', myviews.recom_redirect, name='recom_redirect'),
]

SearchEngine/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.search, name='search'),
    url(r'^search_result/.*$', views.search_result, name='search_result'),
    url(r'^signup/', views.signup_view, name='signup'),
]

SearchEngine/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.contrib.postgres.fields import ArrayField
from django.utils import timezone


class SearchQuery(models.Model):
    user = models.ForeignKey('auth.User')
    word = models.CharField(max_length=100)
    servers = ArrayField(models.CharField(max_length=100, blank=True))
    search_date = models.DateTimeField(default=timezone.now)

    def add(self, **kwargs):
        self.search_date = timezone.now()
        self.word = kwargs['word']
        self.servers = kwargs['servers']
        self.save()

    def __str__(self):
        return self.word


class Server(models.Model):
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=200)
    data = JSONField()

    def __str__(self):
        return self.name


class Path(models.Model):
    path = models.TextField()
    files = ArrayField(models.CharField(max_length=300))
    keywords = ArrayField(models.CharField(max_length=100))
    server_name = models.CharField(max_length=50)
    metadata = models.CharField(max_length=200)

    def __str__(self):
        return self.path


class ServerName(models.Model):
    name = models.CharField(max_length=100)
    path = models.CharField(max_length=200)
    server = models.OneToOneField(Server,
                                  on_delete=models.CASCADE,
                                  primary_key=True,)
    creation_date = models.DateTimeField(default=timezone.now)

    def add(self):
        self.creation_date = timezone.now()
        self.save()

    def __str__(self):
        return self.name

    def __repr__(self):
        return "name: {} | path: {}".format(self.name, self.path)


class WordNet(models.Model):
    word = models.CharField(max_length=200)
    similars = ArrayField(models.CharField(max_length=200, blank=True))

    def __str__(self):
        return self.word
    
    def add(self):
        self.save()


class Recommendation(models.Model):
    user = models.OneToOneField('auth.User')
    recommendations = JSONField()

    def __str__(self):
        return str(self.user)

SearchEngine/forms.py
from django import forms
from .models import SearchQuery, ServerName


class SearchForm(forms.ModelForm):

    class Meta:
        model = SearchQuery
        fields = ('word',)
        widgets = {'word': forms.TextInput(attrs={'placeholder': "search for data",
        		  								  'class': 'form-control',},),}
        labels = {
        "word": ""
        }


class SelectServer(forms.Form):
    servers = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                        choices=[],
                                        required=False)

    def __init__(self, *args, **kwargs):
        super(SelectServer, self).__init__(*args, **kwargs)
        self.fields['servers'].choices = [(x.path, x.name) for x in ServerName.objects.all()]
        self.fields['servers'].widget.attrs['class'] = "dropdown show"

SearchEngine/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.csrf import csrf_exempt
from django.core.cache import cache
from SearchEngine.lib.utils import FindSearchResult
from .models import SearchQuery, Recommendation, ServerName
from .forms import SearchForm
from itertools import islice
from collections import Counter
import json


def home(request):
    recommendations = Recommendation.objects.all()
    return render(request, 'SearchEngine/base.html',
                  {})

def user_profile(request):
    pass


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


@csrf_exempt
def search_result(request, page=1):
    # query = get_object_or_404(Search, pk=pk)
    global all_result
    global founded_results
    keyword = request.POST.get('keyword')
    if keyword is None:
        # Changing the page
        page = request.GET.get('page', 1)
        paginator = Paginator(all_result, 20)
        try:
            results = paginator.page(page)
        except PageNotAnInteger:
            results = paginator.page(1)
        except EmptyPage:
            results = paginator.page(paginator.num_pages)
        error = None
    else:
        selected = json.loads(request.POST.get('selected'))
        # csrftoken = request.POST.get('csrfmiddlewaretoken')
        search_model = SearchQuery()
        search_model.user = request.user
        search_model.add(word=keyword, servers=list(selected))

        searcher = FindSearchResult(keyword=keyword, servers=selected, user=request.user)
        try:
            all_result = list(searcher.find_result())
            paginator = Paginator(all_result, 20)
            results = paginator.page(1)
            # cache.set('search_result', all_result, None)
            error = False
            founded_results = len(all_result)
        except ValueError as exc: 
            # invalid keyword
            error = """INVALID KEYWORD:
            Your keyword contains invalid notations!
            {}""".format(exc)
            print(error)
            results = paginator.page(0)
    index = results.number - 1
    max_index = len(paginator.page_range)
    start_index = index - 3 if index >= 3 else 0
    end_index = index + 3 if index <= max_index - 3 else max_index
    page_range = list(paginator.page_range)[start_index:end_index]
    if keyword is None:
        return render(request, 'SearchEngine/page_format.html',
                            {'all_results': results,
                             'error': error,
                             'founded_results': founded_results,
                             'user': request.user,
                             'page_range': page_range})
    else:
        html = render_to_string('SearchEngine/page_format.html',
                            {'all_results': results,
                             'error': error,
                             'founded_results': founded_results,
                             'user': request.user,
                             'page_range': page_range,
                             'selected_len': len(selected)})
        return HttpResponse(json.dumps({'html': html}), content_type="application/json")

@login_required()
def recom_redirect(request, keyword):
    servers = ServerName.objects.all()
    selected = {s.name: s.path for s in servers}
    searcher = FindSearchResult(keyword=keyword, servers=selected, user=request.user)
    all_result = list(searcher.find_result())
    paginator = Paginator(all_result, 20)
    results = paginator.page(1)
    error = False
    founded_results = len(all_result)
    index = results.number - 1
    max_index = len(paginator.page_range)
    start_index = index - 3 if index >= 3 else 0
    end_index = index + 3 if index <= max_index - 3 else max_index
    page_range = list(paginator.page_range)[start_index:end_index]
    return render(request, 'SearchEngine/page_format.html',
                            {'all_results': results,
                             'error': error,
                             'founded_results': founded_results,
                             'user': request.user,
                             'page_range': page_range,
                             'selected_len': len(selected)})

@csrf_exempt
@login_required()
def search(request):
    search_form = SearchForm()
    servers = ServerName.objects.all()
    queryset = Recommendation.objects.filter(user=request.user)

    try:
        recom_model = queryset[0]
    except IndexError:
        recomwords = []
    else:
        recomwords = Counter(recom_model.recommendations).most_common(7)
    return render(request, 'SearchEngine/search.html',
                  {'search_form': search_form,
                   'servers': servers,
                   'user': request.user,
                   'recommended_words': recomwords})

SearchEngine/templates/SearchEngine/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

SearchEngine/templates/SearchEngine/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Airport</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=IM+Fell+English+SC|Spectral" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/searchengine.css' %}">
        <script type="text/javascript" src="{% static 'js/searchengine.js' %}"></script> 
        <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto">
          <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" type="text/css" href="{% static 'css/multi-select.css' %}">
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
  <!-- Bootstrap JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="{% static 'js/jquery.multi-select.js' %}"></script>
    </head>
    <body>
    <div class="page-header">
        {% if user.is_authenticated %}
            <p class="top-menu"><b>{{ user.username }}</b> <<a href="{% url 'logout' %}">Log out</a>></p>
        {% else %}
            <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
        {% endif %}
        <h1><a href="/">Airport</a></h1>
        <img id="header_image" src="{% static 'img/Airport_logo_min.png' %}">
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-offset-2">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
    </body>
    <script type="text/javascript">
        $("#id_word").keyup(function(event) {
            if (event.keyCode === 13) {
                $("#submit_search").click();
            }
        })
    </script>
  <script type="text/javascript">
  // run pre selected options
    $('#pre-selected-options').multiSelect();
    $('#select-all').click(function(){
    $('#pre-selected-options').multiSelect('select_all');
        return false;
        });
    $('#deselect-all').click(function(){
    $('#pre-selected-options').multiSelect('deselect_all');
        return false;
        });
    $("submit_search").click(function(){search_result()})
  </script>

</html>

SearchEngine/templates/SearchEngine/page_format.html
{% extends 'SearchEngine/base.html' %}
{% block content %}
<p> <b>{{ founded_results }} results founded</b> </p>
{% if not selected_len %}
 <p style="color:red"> <b> NO SERVER IS SELECTED! </b> </p>

{% else %}
<table class="table table-bordered">
    <thead>
      <tr>
        <th>Path</th>
        <th>Exact match</th>
        <th>Server name</th>
        <th>Search for metadata</th>
      </tr>
    </thead>
    <tbody>
      {% for record in all_results %}
        <tr>
          {% if record.exact_match %}
              <td><a href= 'ftp://{{ record.url }}{{ record.path }}' 
            target="_blank" style="color:#008211">{{ record.path }}</a></td>
          {% else %}
              <td><a href= 'ftp://{{ record.url }}{{ record.path }}' 
            target="_blank">{{ record.path }}</a></td>
          {% endif %}
          <td>{{ record.exact_match }}</td>
          <td>{{ record.name }}</td>
          <td><a href= "{{record.metadata}}" target="_blank">{{record.metadata}}</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  
  {% if all_results.has_other_pages %}
    <ul class="pagination">
      {% if all_results.has_previous %}
        <li><a href="/search_result/?page={{ all_results.previous_page_number }}"
          onclick="return chagne_page()" id="change_page_id">&laquo;</a></li>
      {% else %}
        <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in page_range %}
        {% if all_results.number == i %}
          <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          <li><a href="/search_result/?page={{ i }}" onclick="return chagne_page()" id="change_page_id">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if all_results.has_next %}
        <li><a href="/search_result/?page={{ all_results.next_page_number }}"
          onclick="return chagne_page()" id="change_page_id">&raquo;</a></li>
      {% else %}
        <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
  {% endif %}
{% endif %}
  {% endblock %}

SearchEngine/templates/SearchEngine/search.html
{% extends 'SearchEngine/base.html' %}
{% block content %}
    <h1>Select server</h1>
    <p class="select-all"><a href='#' id='select-all'>select all</a></p>
	<p class="deselect-all"><a href='#' id='deselect-all'>deselect all</a></p>
    <form id='pre-selected-options' multiple='multiple'>{% csrf_token %}
    	{% for name in servers %}
    		<option value={{name.path}} title={{name.path}}>{{name}}</option>
    	{% endfor %}
    </form>
    <h1>Enter your Keyword here</h1>
    <div class="post-form" >
        {{ search_form.as_p }}
        <button id="submit_search" class="save btn btn-default" 
        onclick="return search_result()" type="submit">Search</button>
    </div>
    {% if user.is_authenticated %}
        <div class="recommendations">
            <ul>
                <p> Recommended words for you: </p>
                {% for word in recommended_words %}
                <li><a href="{% url 'recom_redirect' keyword=word.0 %}" >{{word.0}}</a></li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

SearchEngine/templates/SearchEngine/search_result.html
{% extends 'SearchEngine/base.html' %}

{% block content %}
	<p> <b>{{ founded_results }} results founded</b> </p>
	{% if all_results.1.data %}
	<li>{{ all_results.0 }}</li>
		<ul>
			{% for dict in all_results.1.data%}
				<li><a href= 'ftp://{{ meta.url }}{{ dict.path }}' target="_blank"> {{ dict.path }} </a></li>
			{% endfor %}
		</ul>
	{% endif %}
	<ul class="pagination">
		<li class="active"><span>1 <span class="sr-only">(current)</span></span></li>
		<li><a href="search_result/2">&raquo;</a></li>
{% endblock %}